config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # main controller
  root 'main#index'

  get '/accommodations', to: 'accommodations#index'

  get '/amenities', to: 'amenities#index'

  get '/reservations', to: 'reservations#index'
  get '/reservations/new', to: 'reservations#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]

  namespace :user do
    get '/profile', to: 'profile#index'
    get '/profile/info', to: 'profile#show'
    get '/profile/edit', to: 'profile#edit_info'
    patch '/profile', to: 'profile#update_info'
    get '/profile/password', to: 'profile#edit_password'
    patch '/profile/password', to: 'profile#update_password'

    resources :reservations, only: [:index, :show, :new, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :username, :first_name, :last_name, :phone, :address, :city, :state, :zip
  validates :username, uniqueness: true, presence: true
  validates :password, presence: true, :on => :create

  has_secure_password

  enum role: %w(user admin)

  has_many :reservations

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/user/base_controller.rb
class User::BaseController < ApplicationController
  before_action :require_user

    def require_user
      render file: "/public/404" unless current_user?
    end
end

app/controllers/user/bookings_controller.rb
class User::BookingsController < User::BaseController
  def new
    @room = Room.find(params[:room])
  end

  def create
    room = Room.find(params[:room])
    Reservation.create(user_id: current_user.id,
                       room_id: room.id,
                       check_in: current_search.check_in,
                       check_out: current_search.check_out,
                       guests: current_search.guests,
                       total_cost: current_search.total_cost(room.price))
    redirect_to user_billing_index_path
  end
end

app/controllers/user/profile_controller.rb
class User::ProfileController < User::BaseController
  def index
    @date = Date.today
    @weather = weather_api
  end

  def show
  end

  def edit_info
    @user = current_user
  end

  def update_info
    if current_user.update(user_params)
      flash[:success] = 'Update information successfully'
      redirect_to user_profile_info_path
    else
      flash[:error] = current_user.errors.full_messages.first
      redirect_to user_profile_edit_path
    end
  end

  def edit_password

  end

  def update_password
    if params[:password].split.count > 0
      current_user.update_attribute(:password, params[:password])
      flash[:success] = "Password successfully changed!"
      redirect_to user_profile_info_path
    else
      flash[:error] = "Password cannot be blank"
      redirect_to user_profile_edit_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,
                                 :first_name,
                                 :last_name,
                                 :address,
                                 :city,
                                 :state,
                                 :zip)
  end

  def weather_api
    response = Faraday.get "https://api.weatherbit.io/v2.0/current?city=Denver,CO&key=740a67e52c784d82ad507f463d022391"
    body = JSON(response.body)
    body['data'].first
  end
end

app/controllers/user/reservations_controller.rb
class User::ReservationsController < User::BaseController
  def index
    @reservations = current_user.reservations
  end

  def show
    @reservation = Reservation.select("reservations.*, rooms.beds, rooms.image, rooms.description, rooms.price, rooms.river_view").joins(:room).find(params[:id])
  end

  def new
    @room = Room.find(params[:room])
  end

  def create
    room = Room.find(params[:room])
    Reservation.create(user_id: current_user.id,
                       room_id: room.id,
                       check_in: current_search.check_in,
                       check_out: current_search.check_out,
                       guests: current_search.guests,
                       total_cost: current_search.total_cost(room.price))
    redirect_to user_reservations_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_profile_path
    else
      flash[:error] = @user.errors.full_messages.first
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,
                                 :password,
                                 :first_name,
                                 :last_name,
                                 :phone,
                                 :address,
                                 :city,
                                 :state,
                                 :zip)
  end
end

app/views/user/profile/_nav_profile.html.erb
<section class='profile-nav'>
  <div class='profile-nav-link' id='profile-overview'>
    <%= link_to 'Overview', user_profile_path %><br><br>
  </div>
  <div class='profile-nav-link' id='profile-activities'>
    <%= link_to 'Activities', '' %><br><br>
  </div>
  <div class='profile-nav-link' id='profile-billing'>
    <%= link_to 'Billing', '' %><br><br>
  </div>
  <div class='profile-nav-link' id='profile-profile'>
    <%= link_to 'Profile', user_profile_info_path %><br><br>
  </div>
</section>

app/views/user/profile/edit.html.erb
<div class='profile-container'>
  <div class='welcome-message'>
    <%= render partial: "header" %>
  </div>
  <article class='profile-main'>
    <%= render partial: "nav_profile" %>
    <section class='profile-content'>
      <%= form_for @user, url: '/user/profile/' do |f| %>
        <div class="row">
          <div class="col">
            <%= f.label 'Username/email' %><br>
            <%= f.text_field :username, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'First Name' %><br>
            <%= f.text_field :first_name, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'Last Name' %><br>
            <%= f.text_field :last_name, required: true %><br><br>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.label 'Address' %><br>
            <%= f.text_field :address, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'City' %><br>
            <%= f.text_field :city, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'State' %><br>
            <%= f.text_field :state, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'Zip' %><br>
            <%= f.text_field :zip, required: true %><br><br>
          </div>
        </div>
        <div class="row">
          <%= f.submit %>
        </div>
      <% end %>
    </section>
  </article>
</div>

app/views/user/profile/edit_info.html.erb
<div class='profile-container'>
  <div class='welcome-message'>
    <%= render partial: "/user/header" %>
  </div>
  <article class='profile-main'>
    <%= render partial: "/user/nav_profile" %>
    <section class='profile-content'>
      <%= form_for @user, url: '/user/profile/' do |f| %>
        <div class="row">
          <div class="col">
            <%= f.label 'Username/email' %><br>
            <%= f.text_field :username, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'First Name' %><br>
            <%= f.text_field :first_name, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'Last Name' %><br>
            <%= f.text_field :last_name, required: true %><br><br>
          </div>
          <div class="col">
          </div>
        </div>
        <div class="row">
          <div class="col">
            <%= f.label 'Address' %><br>
            <%= f.text_field :address, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'City' %><br>
            <%= f.text_field :city, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'State' %><br>
            <%= f.text_field :state, required: true %><br><br>
          </div>
          <div class="col">
            <%= f.label 'Zip' %><br>
            <%= f.text_field :zip, required: true %><br><br>
          </div>
        </div>
        <div class="row">
          <%= f.submit %>
        </div>
      <% end %>
    </section>
  </article>
</div>

app/views/user/profile/edit_password.html.erb
<div class='profile-container'>
  <div class='welcome-message'>
    <%= render partial: "/user/header" %>
  </div>
  <article class='profile-main'>
    <%= render partial: "/user/nav_profile" %>
    <section class='profile-content'>
      <div class="row">
        <h3>Password Update</h3>
      </div>
      <div class="row">
        <div class="col pass-box">
          <%= form_tag '/user/profile/password', method: :patch do %>
            <%= password_field_tag :password %><br><br>
            <%= submit_tag "Update Password" %>
          <% end %>
        </div>
        <div class="col">
          Password must contain:
          <ul>
            <li>At least 6 characters</li>
            <li>Contain one number (0-9)</li>
            <li>One special character (!@#$%^&*)</li>
            <li>One capital letter</li>
          </ul>
        </div>
      </div>

    </section>
  </article>
</div>

app/views/user/profile/index.html.erb
<div class='profile-container'>
  <div class='welcome-message'>
    <%= render partial: "/user/header" %>
  </div>
  <article class='profile-main'>
    <%= render partial: "/user/nav_profile" %>
    <section class='profile-content'>
      <div class="weather">
        <h3>Weather Forcast for <%= @date.strftime("%A %B %d, %Y") %></h3>
        <div class="weather-stats">
          <div class="row">
            <div class="col ws-title">
              Current Temperature
            </div>
            <div class="col ws-title">
              Feels Like
            </div>
            <div class="col ws-title">
              Cloud Coverage Percentage
            </div>
            <div class="col ws-title">
              Description
            </div>
          </div>
          <div class="row">
            <div class="col ws-data">
              <%= @weather['temp'] %> °C
            </div>
            <div class="col ws-data">
              <%= @weather['app_temp'] %> °C
            </div>
            <div class="col ws-data">
              <%= @weather['clouds'] %>%
            </div><div class="col ws-data">
              <%= @weather['weather']['description'] %>
            </div>
          </div>
          <div class="row-* ws-credit">
            Brought to you by Weathbit.io
          </div>
        </div>
      </div>
    </section>
  </article>
</div>

app/views/user/profile/show.html.erb
<div class='profile-container'>
  <div class='welcome-message'>
    <%= render partial: "/user/header" %>
  </div>
  <article class='profile-main'>
    <%= render partial: "/user/nav_profile" %>
    <section class='profile-content'>
      <div class="row">
        <div class="col">
          Username/email <br>
          <%= text_field_tag :username, current_user.username, disabled:true %><br><br>
        </div>
        <div class="col">
          First name <br>
          <%= text_field_tag :first_name, current_user.first_name, disabled:true %><br><br>
        </div>
        <div class="col">
          Last name <br>
          <%= text_field_tag :first_name, current_user.last_name, disabled:true %><br><br>
        </div>
        <div class="col">
        </div>
      </div>
      <div class="row">
        <div class="col">
          Address <br>
          <%= text_field_tag :address, current_user.address, disabled:true %><br><br>
        </div>
        <div class="col">
          City <br>
          <%= text_field_tag :city, current_user.city, disabled:true %><br><br>
        </div>
        <div class="col">
          State <br>
          <%= text_field_tag :state, current_user.state, disabled:true %><br><br>
        </div>
        <div class="col">
          Zip <br>
          <%= text_field_tag :zip, current_user.zip, disabled:true %><br><br>
        </div>
      </div>
      <div class="row">
        <div class="col text-align">
          <div class="text-center">
            <%= link_to "Update Personal Information", user_profile_edit_path %>
          </div>
        </div>
        <div class="col text-align">
          <div class="text-center">
            <%= link_to "Update Password", user_profile_password_path %>
          </div>
        </div>
      </div>
    </section>
  </article>
</div>