config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # main controller
  root 'main#index'

  get '/accommodations', to: 'accommodations#index'

  get '/amenities', to: 'amenities#index'

  get '/reservations', to: 'reservations#index'
  get '/reservations/new', to: 'reservations#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]

  namespace :user do
    get '/profile', to: 'profile#index'
    get '/profile/info', to: 'profile#show'
    get '/profile/edit', to: 'profile#edit_info'
    patch '/profile', to: 'profile#update_info'
    get '/profile/password', to: 'profile#edit_password'
    patch '/profile/password', to: 'profile#update_password'

    resources :reservations, only: [:index, :show, :new, :create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hotel Gari</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>


    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <nav class='navbar'>
      <div class="navbar-left">
        <%= link_to 'Hotel Gari', '/', class: 'navbar-link', id: 'company-title' %>
      </div>
      <div class="navbar-right">
        <%= link_to 'ACCOMMODATIONS', '/accommodations', class: 'navbar-link' %>
        <%= link_to 'AMENITIES', '/amenities', class: 'navbar-link' %>
        <%= link_to "RESERVE", '/reservations', class: 'navbar-link' %>
        <% if current_user %>
          <%= link_to "DASHBOARD", user_profile_path, class: 'navbar-link' %>
        <% else %>
          <%= link_to "LOGIN", '/login', class: 'navbar-link' %>
        <% end %>
      </div>
    </nav>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class= "<%=name%>-flash">
        <p><%= msg %></p>
      </div>
      <% end %>
    <%= yield %>
  </body>
</html>